plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.uniidcardcapture.demo'
    compileSdk 34

    defaultConfig {
        applicationId 'io.github.uniidcardcapture.demo'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildFeatures {
        buildConfig false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':idcardcapture')
}
